### ISSUE TITLE
Interface Issues

### ISSUE THREAD

**Issue by vitalielias** [kit-data-manager/mapping-service#22]
Some are experiencing issues with the (new) interface on the [live instance of the mapping service UI](https://matwerk.datamanager.kit.edu/mapping-service-ui.html). Mainly, the map document button produces no result or response when clicked. This is after clearing cache, cookies, trying in private browsing, etc.

For myself, in Chrome on MacOS, it works as expected. The SEM Tiff to JSON example plugin that is currently uploaded is non-functional however, and the json file produced has the following output:

    {"timestamp":"2023-06-12T09:22:43.658+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/mappingExecution/SEM"}

**Comment by ThomasJejkal** [comment]
Then you are wrong here...Issues with the mapping service component belong here: https://github.com/kit-data-manager/com_mapping-service-input ;-)
