### ISSUE TITLE
Refactor `cloneGitRepository` method to pull when a plugin is run if the repository already exists

### ISSUE THREAD

**Issue by vitalielias** [kit-data-manager/mapping-service#24]
Currently, our `cloneGitRepository` method clones a repository to a target folder. However, if the repository already exists in the target directory, this process is redundant, and doesn't pull the latest version, causing us to have to go and pull the latest changes manually or delete the directory and re-clone it. This needs to be modified to pull changes from the repository if it already exists, rather than re-cloning the entire repository.

To do this, a `getGitRepository` method should be made to replace `cloneGitRepository` which checks whether the target repository already exists, and:

- if it doesn't exist, the method should clone the repository as it currently does;
- if it does exist, the method should instead pull the latest changes from the repository.
- returns the path to the cloned or updated repository

**Comment by vitalielias** [comment]
File in which method should be written: `src/main/java/edu/kit/datamanager/mappingservice/util/FileUtil.java`

**Comment by ThomasJejkal** [comment]
Fixed in the next version. Then, 'Reload Plugins' called from the 'Add mapping scheme' tab in the UI will issue a Git pull if a repository already exists locally.
